# Generated by Django 5.1.6 on 2025-03-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_classification', models.CharField(choices=[('A', 'Low Risk'), ('B', 'Medium Risk'), ('C', 'High Risk'), ('D', 'Critical Risk')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=255)),
                ('reporter_type', models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Importer', 'Importer'), ('Healthcare Professional', 'Healthcare Professional'), ('Patient', 'Patient'), ('Other', 'Other')], max_length=100)),
                ('event_description', models.TextField()),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Critical', 'Critical')], max_length=50)),
                ('corrective_action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='reg_app.medicaldevice')),
            ],
        ),
    ]
