# Generated by Django 5.1.6 on 2025-03-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
