# Generated by Django 4.2.19 on 2025-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerupdate', '0002_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
