# Generated by Django 5.1.6 on 2025-03-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_app', '0002_otpmodel_delete_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='created_at',
        ),
    ]
